[package]
name = "rust_bench_sets_compared"
version = "0.1.0"
authors = ["Stein Somers <git@steinsomers.be>"]
edition = "2018"

[dev-dependencies]
proptest = "0.9"

[dependencies]
fnv = "1.0.6"
hashbrown = "0.6"
